---
# Tasks file for roles/ronly-gather-vms
- name: Ensure required Python packages are installed (user scope)
  ansible.builtin.pip:
    name: "{{ item.name }}=={{ item.version }}"
    executable: pip3
  loop: "{{ user_pip_packages }}"

- name: Get teh available Droplets info
  digitalocean.cloud.droplets_info:
    token: "{{ token }}"
  register: droplets

- debug:
    msg: "Retrieved {{ droplets.droplets | length }} droplets."

- name: Check if specified droplets exist
  set_fact:
    found_droplets: "{{ lookup_droplets | map('extract', droplets_map) | select('defined') | list }}"
  vars:
    droplets_map: "{{ droplets.droplets | items2dict(key_name='name', value_name='id') }}"
    lookup_droplets: "{{ search_droplets | default([]) }}"

- debug:
    msg: "present-yes"
  when: found_droplets | length > 0
