---
# Tasks file for roles/ronly-gather-vms
- name: Ensure required Python packages are installed (user scope)
  ansible.builtin.pip:
    name: "{{ item.name }}=={{ item.version }}"
    executable: pip3
  loop: "{{ user_pip_packages }}"

- name: Get teh available Droplets info
  digitalocean.cloud.droplets_info:
    token: "{{ token }}"
  register: droplets

- debug:
    var: "{{ droplets.droplets.msg }}"
    
- name: Extract id and name using json_query
  set_fact:
    droplet_response: "{{ droplets.droplets.msg }}"
    droplet_summary: "{{ droplet_response.json.droplets.msg | json_query('[].{id: id, name: name}') }}"

- debug:
    var: droplet_summary