---
# Tasks file for roles/ronly-gather-vms
- name: Ensure required Python packages are installed (user scope)
  ansible.builtin.pip:
    name: "{{ item.name }}=={{ item.version }}"
    executable: pip3
  loop: "{{ user_pip_packages }}"

# - name: Get VPCs
#   digitalocean.cloud.vpcs_info:
#     token: "{{ token }}"
#   register: vpcs

- name: Get VPCs
  digitalocean.cloud.droplets_info:
    token: "{{ token }}"
  register: droplets

- name: print the available VPCs
  ansible.builtin.debug:
    msg: "{{ droplets.droplets }}"